# properties_data.py
# Только объекты, которые есть в Service_South.xlsx (совпадение по тикеру).
# Источник цен: Price-info table (Capital Pro), 11 сезонных периодов, THB.
# Поля parking / pets_allowed / kids_friendly убраны - таких данных нет в источниках.
# Поле "status" убрано - статус (свободно/занято) уточняется у менеджера.

PROPERTIES = [
    {
        "id": 'CHC-A402',
        "type": 'apartment',
        "title": 'Chic_Condo A402',
        "district": 'Karon',
        "bedrooms": 0,
        "sqm": '47',
        "view": 'sea view',
        "pool_access": 'common',
        "address": '8/52 Soi Patak Soi 20, Karon Subdistrict Muang District Phuket 83100',
        "map_link": 'https://maps.app.goo.gl/yUARcpnCMQjsC9YD6',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/11aF_nIlq8QHQM-40kAHbcPod96FWp_TM?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 69000, "price_night_thb": 2300},
            {"period": 'Апрель', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 21000, "price_night_thb": 700},
            {"period": 'Сентябрь', "price_month_thb": 18000, "price_night_thb": 600},
            {"period": 'Октябрь', "price_month_thb": 33000, "price_night_thb": 1100},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 84000, "price_night_thb": 2800},
            {"period": '15–31 декабря', "price_month_thb": 105000, "price_night_thb": 3500},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'PRO-613',
        "type": 'apartment',
        "title": 'The Proud Condominium B613',
        "district": 'Karon',
        "bedrooms": 1,
        "sqm": '35',
        "view": 'sea view',
        "pool_access": 'common',
        "address": '2 Patak Rd, Karon, Mueang Phuket District, Phuket 83100',
        "map_link": 'https://maps.app.goo.gl/cAsGueCm5q8V7Mfu9',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/1zFy_VCBo1OEHihdK7gUgrc8rbCbE8Ck2?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 135000, "price_night_thb": 4500},
            {"period": 'Февраль', "price_month_thb": 99000, "price_night_thb": 3300},
            {"period": 'Март', "price_month_thb": 84000, "price_night_thb": 2800},
            {"period": 'Апрель', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Май', "price_month_thb": 33000, "price_night_thb": 1100},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 21000, "price_night_thb": 700},
            {"period": 'Октябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Ноябрь', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": '1–15 декабря', "price_month_thb": 78000, "price_night_thb": 2600},
            {"period": '15–31 декабря', "price_month_thb": 135000, "price_night_thb": 4500},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'SPL-101',
        "type": 'apartment',
        "title": 'Splendid_Condo 1101',
        "district": 'Kata',
        "bedrooms": 0,
        "sqm": '26',
        "view": 'greenery view',
        "pool_access": 'common',
        "address": '10/8 Soi Patak Soi 2, Karon Subdistrict Muang District Phuket ',
        "map_link": 'https://maps.app.goo.gl/BhfoMYuHfnSgQ74o9',
        "max_guests": None,
        "links": ['https://drive.google.com/drive/folders/14A7oZ_GZSaSuejYTQd0N6qq0uzhJoBzE?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 84000, "price_night_thb": 2800},
            {"period": 'Февраль', "price_month_thb": 48000, "price_night_thb": 1600},
            {"period": 'Март', "price_month_thb": 42000, "price_night_thb": 1400},
            {"period": 'Апрель', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Май', "price_month_thb": 27000, "price_night_thb": 900},
            {"period": 'Июнь–Август', "price_month_thb": 18000, "price_night_thb": 600},
            {"period": 'Сентябрь', "price_month_thb": 15000, "price_night_thb": 500},
            {"period": 'Октябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": '15–31 декабря', "price_month_thb": 84000, "price_night_thb": 2800},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'UTN-C206',
        "type": 'apartment',
        "title": 'Utopia Condo C206',
        "district": 'Naiharn',
        "bedrooms": 1,
        "sqm": '45.24',
        "view": 'garden/building',
        "pool_access": 'common',
        "address": '3/155 Soi Suan Wat, Moo 1, Rawai, Mueang Phuket, Thailand 83130',
        "map_link": 'To the left of the reception desk is the entrance to Building C.\nLink to the main entrance (reception).\nhttps://maps.app.goo.gl/CpXyJHLAVfRZ2NKH8?g_st=ic',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/10Ut-ogCu8He-zINh8BgyFEFbXc0UgNcp?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 120000, "price_night_thb": 4000},
            {"period": 'Февраль', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Март', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Апрель', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Май', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": '15–31 декабря', "price_month_thb": 120000, "price_night_thb": 4000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'CGC-310',
        "type": 'apartment',
        "title": 'Calypso Garden Condominium310',
        "district": 'Naiharn',
        "bedrooms": 2,
        "sqm": '78',
        "view": 'garden view',
        "pool_access": 'common',
        "address": '88/122 Soi Thaweesaman, Moo 2, Rawai, Mueang Phuket, Thailand 83130',
        "map_link": 'https://maps.app.goo.gl/j7zSkSQ1VbVEkmv29',
        "max_guests": 5.0,
        "links": ['https://drive.google.com/drive/folders/1rvtnv9viRH7A89OH_FKjOT7VGf6S0U64?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 255000, "price_night_thb": 8500},
            {"period": 'Февраль', "price_month_thb": 195000, "price_night_thb": 6500},
            {"period": 'Март', "price_month_thb": 120000, "price_night_thb": 4000},
            {"period": 'Апрель', "price_month_thb": 84000, "price_night_thb": 2800},
            {"period": 'Май', "price_month_thb": 54000, "price_night_thb": 1800},
            {"period": 'Июнь–Август', "price_month_thb": 51000, "price_night_thb": 1700},
            {"period": 'Сентябрь', "price_month_thb": 54000, "price_night_thb": 1800},
            {"period": 'Октябрь', "price_month_thb": 84000, "price_night_thb": 2800},
            {"period": 'Ноябрь', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": '1–15 декабря', "price_month_thb": 120000, "price_night_thb": 4000},
            {"period": '15–31 декабря', "price_month_thb": 255000, "price_night_thb": 8500},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'NBC-A202',
        "type": 'apartment',
        "title": 'Naiharn Beach Condo A202',
        "district": 'Naiharn',
        "bedrooms": 1,
        "sqm": '47',
        "view": 'greenery view common',
        "pool_access": '-',
        "address": '3/30 Soi Suan Wat, Moo 1, Rawai, Mueang Phuket, Thailand 83130',
        "map_link": 'https://maps.app.goo.gl/ZfR6aoPdjotjLgn58',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/1-_t72Vb6SRSjhuV6Y55loHgputHQjdpW?usp=share_link', 'https://telegra.ph/NaiHarn-Beach-Condo-08-06'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Февраль', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Март', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Апрель', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": '15–31 декабря', "price_month_thb": 105000, "price_night_thb": 3500},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'NBC-A807',
        "type": 'apartment',
        "title": 'Naiharn Beach Condo A807',
        "district": 'Naiharn',
        "bedrooms": 1,
        "sqm": '36',
        "view": 'mountain/building',
        "pool_access": 'common',
        "address": '3/578 Soi Suan Wat, Moo 1, Rawai, Mueang Phuket, Thailand 83130',
        "map_link": 'https://maps.app.goo.gl/vbsYwXuBm5SqKsHB6?g_st=ic',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/17IWEbustTsa0ABm_sAdIxP6JAbZSq2tA?usp=share_link', 'https://telegra.ph/Naiharn-Beach-Condo-08-06-2'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 108000, "price_night_thb": 3600},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Апрель', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": '15–31 декабря', "price_month_thb": 108000, "price_night_thb": 3600},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'NBC-C102',
        "type": 'apartment',
        "title": 'Naiharn Beach Condo C102',
        "district": 'Naiharn',
        "bedrooms": 0,
        "sqm": '56',
        "view": 'garden/pool view',
        "pool_access": 'common',
        "address": '3/89 Soi Suan Wat, Moo 1, Rawai, Mueang Phuket, Thailand 83130',
        "map_link": 'https://maps.app.goo.gl/dxSsoowq6EnYqAKL9',
        "max_guests": 4.0,
        "links": ['https://drive.google.com/drive/folders/1uVB5FEFJmeQaWrxYxNY0roCtR0ebGwjM?usp=share_link', 'https://telegra.ph/NBC-Condo-08-17-2'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Февраль', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": 'Март', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Апрель', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Май', "price_month_thb": 33000, "price_night_thb": 1100},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 42000, "price_night_thb": 1400},
            {"period": 'Ноябрь', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": '1–15 декабря', "price_month_thb": 84000, "price_night_thb": 2800},
            {"period": '15–31 декабря', "price_month_thb": 105000, "price_night_thb": 3500},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'NBC-C503',
        "type": 'apartment',
        "title": 'Naiharn Beach Condo C503',
        "district": 'Naiharn',
        "bedrooms": 0,
        "sqm": '58',
        "view": 'greenery view',
        "pool_access": 'common',
        "address": '3/110 Soi Suan Wat, Moo 1, Rawai, Mueang Phuket, Thailand 83130',
        "map_link": 'https://maps.app.goo.gl/dxSsoowq6EnYqAKL9',
        "max_guests": 4.0,
        "links": ['https://drive.google.com/drive/folders/1yqUNJTzj2sP66JX-HM8q5BfhdDDZ6qlo?usp=share_link', 'https://telegra.ph/NBC-Condo-08-17-3'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 114000, "price_night_thb": 3800},
            {"period": 'Февраль', "price_month_thb": 96000, "price_night_thb": 3200},
            {"period": 'Март', "price_month_thb": 84000, "price_night_thb": 2800},
            {"period": 'Апрель', "price_month_thb": 54000, "price_night_thb": 1800},
            {"period": 'Май', "price_month_thb": 39000, "price_night_thb": 1300},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 51000, "price_night_thb": 1700},
            {"period": 'Ноябрь', "price_month_thb": 69000, "price_night_thb": 2300},
            {"period": '1–15 декабря', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": '15–31 декабря', "price_month_thb": 114000, "price_night_thb": 3800},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'NBC-P709',
        "type": 'apartment',
        "title": 'Naiharn Beach Condo P709',
        "district": 'Naiharn',
        "bedrooms": 1,
        "sqm": '36',
        "view": 'building view',
        "pool_access": 'common',
        "address": '3/652 Soi Suan Wat, Moo 1, Rawai, Mueang Phuket, Thailand 83130',
        "map_link": 'https://maps.app.goo.gl/vbsYwXuBm5SqKsHB6?g_st=ic',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/18H2mas__Hak_WMx2_UJz9JcO2I-5zgIr?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 108000, "price_night_thb": 3600},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Апрель', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": '15–31 декабря', "price_month_thb": 108000, "price_night_thb": 3600},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'NBC-P809',
        "type": 'apartment',
        "title": 'Naiharn Beach Condo P809',
        "district": 'Naiharn',
        "bedrooms": 1,
        "sqm": '36',
        "view": 'building view',
        "pool_access": 'common',
        "address": '3/661 Soi Suan Wat, Moo 1, Rawai, Mueang Phuket, Thailand 83130',
        "map_link": 'https://maps.app.goo.gl/VajRavyhGEaDX1qk9',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/1Mx9Z74KIQJKL1Dux2H6mQgJQBdnVhJYm?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 108000, "price_night_thb": 3600},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Апрель', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": '15–31 декабря', "price_month_thb": 108000, "price_night_thb": 3600},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'NBC-P810',
        "type": 'apartment',
        "title": 'Naiharn Beach Condo P810',
        "district": 'Naiharn',
        "bedrooms": 1,
        "sqm": '36',
        "view": 'building view',
        "pool_access": 'common',
        "address": '3/662 Soi Suan Wat, Moo 1, Rawai, Mueang Phuket, Thailand 83130',
        "map_link": 'https://maps.app.goo.gl/VajRavyhGEaDX1qk9',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/1Xjld1uKZge7Ciy1a1U0lV7P_6W8S5rlt?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 108000, "price_night_thb": 3600},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Апрель', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": '15–31 декабря', "price_month_thb": 108000, "price_night_thb": 3600},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'REW-B226',
        "type": 'apartment',
        "title": 'Relife The Windy B226',
        "district": 'Naiharn',
        "bedrooms": 0,
        "sqm": '30',
        "view": 'street view',
        "pool_access": 'common',
        "address": '15/212 Moo 1, Rawai, Muang, Phuket, Thailand, 83130',
        "map_link": 'https://goo.gl/maps/J2GDML9jURLsWuzX6',
        "max_guests": None,
        "links": ['https://drive.google.com/drive/folders/16MhKBStYv9N8OsXwVemtWeGBKKdu6KeQ?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 99000, "price_night_thb": 3300},
            {"period": 'Февраль', "price_month_thb": 69000, "price_night_thb": 2300},
            {"period": 'Март', "price_month_thb": 48000, "price_night_thb": 1600},
            {"period": 'Апрель', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Май', "price_month_thb": 27000, "price_night_thb": 900},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Ноябрь', "price_month_thb": 54000, "price_night_thb": 1800},
            {"period": '1–15 декабря', "price_month_thb": 66000, "price_night_thb": 2200},
            {"period": '15–31 декабря', "price_month_thb": 99000, "price_night_thb": 3300},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'REW-B315',
        "type": 'apartment',
        "title": 'Relife The Windy B315',
        "district": 'Naiharn',
        "bedrooms": 0,
        "sqm": '30',
        "view": 'greenery view',
        "pool_access": 'common',
        "address": '15/251 Moo 1, Rawai, Muang, Phuket, Thailand, 83130',
        "map_link": 'https://goo.gl/maps/J2GDML9jURLsWuzX6',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/1BYOcb_sQCsI8rHfmvnSXnDk08J4-RTqC?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 57000, "price_night_thb": 1900},
            {"period": 'Апрель', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Май', "price_month_thb": 27000, "price_night_thb": 900},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Ноябрь', "price_month_thb": 57000, "price_night_thb": 1900},
            {"period": '1–15 декабря', "price_month_thb": 69000, "price_night_thb": 2300},
            {"period": '15–31 декабря', "price_month_thb": 105000, "price_night_thb": 3500},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'REW-B725',
        "type": 'apartment',
        "title": 'Relife The Windy B725',
        "district": 'Naiharn',
        "bedrooms": 0,
        "sqm": '30',
        "view": 'mountain view',
        "pool_access": 'common',
        "address": '15/315 Moo 1, Rawai, Muang, Phuket, Thailand, 83130',
        "map_link": 'https://goo.gl/maps/J2GDML9jURLsWuzX6',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/193gIt3A-vw5UAFyUpGZdGjjskPNs9Snx?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Апрель', "price_month_thb": 48000, "price_night_thb": 1600},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Ноябрь', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": '1–15 декабря', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": '15–31 декабря', "price_month_thb": 105000, "price_night_thb": 3500},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'REW-B726',
        "type": 'apartment',
        "title": 'Relife The Windy B726',
        "district": 'Naiharn',
        "bedrooms": 0,
        "sqm": '30',
        "view": 'mountain view',
        "pool_access": 'common',
        "address": '15/314 Moo 1, Rawai, Muang, Phuket, Thailand, 83130',
        "map_link": 'https://goo.gl/maps/J2GDML9jURLsWuzX6',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/19FzkbqPZ3U5ueleup7Dllrtgi2vDkEQ3?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Апрель', "price_month_thb": 48000, "price_night_thb": 1600},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Сентябрь', "price_month_thb": 24000, "price_night_thb": 800},
            {"period": 'Октябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Ноябрь', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": '1–15 декабря', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": '15–31 декабря', "price_month_thb": 105000, "price_night_thb": 3500},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'KOK-45/8',
        "type": 'villa',
        "title": 'Kokyang Villa 45/8',
        "district": 'Naiharn',
        "bedrooms": 3,
        "sqm": '281.32',
        "view": '',
        "pool_access": 'private',
        "address": '45/8, Rawai, Mueang Phuket, Phuket, Thailand, 83130',
        "map_link": 'https://maps.app.goo.gl/CpTBEBWvCizaedmP8',
        "max_guests": None,
        "links": ['https://drive.google.com/drive/folders/1lkhRwzeOE6DRCRT5f1jjHFSeXsAsMynD?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 360000, "price_night_thb": 12000},
            {"period": 'Февраль', "price_month_thb": 270000, "price_night_thb": 9000},
            {"period": 'Март', "price_month_thb": 240000, "price_night_thb": 8000},
            {"period": 'Апрель', "price_month_thb": 210000, "price_night_thb": 7000},
            {"period": 'Май', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Июнь–Август', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": 'Сентябрь', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": 'Октябрь', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Ноябрь', "price_month_thb": 150000, "price_night_thb": 5000},
            {"period": '1–15 декабря', "price_month_thb": 270000, "price_night_thb": 9000},
            {"period": '15–31 декабря', "price_month_thb": 360000, "price_night_thb": 12000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'SIG-101/1',
        "type": 'villa',
        "title": 'Signature Villa 101/1',
        "district": 'Naiharn',
        "bedrooms": 4,
        "sqm": None,
        "view": 'garden view',
        "pool_access": 'private',
        "address": '101/1 Moo 1, Soi Naya 1, Mueang Phuket District, Phuket 83130',
        "map_link": 'https://goo.gl/maps/LbSdgKsDBhXkVxmo7',
        "max_guests": 9.0,
        "links": ['https://drive.google.com/drive/folders/17y8K1JWaSlEwS5j25syk9ddbIYCIFn1t?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 450000, "price_night_thb": 15000},
            {"period": 'Февраль', "price_month_thb": 330000, "price_night_thb": 11000},
            {"period": 'Март', "price_month_thb": 270000, "price_night_thb": 9000},
            {"period": 'Апрель', "price_month_thb": 210000, "price_night_thb": 7000},
            {"period": 'Май', "price_month_thb": 114000, "price_night_thb": 3800},
            {"period": 'Июнь–Август', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Сентябрь', "price_month_thb": 99000, "price_night_thb": 3300},
            {"period": 'Октябрь', "price_month_thb": 120000, "price_night_thb": 4000},
            {"period": 'Ноябрь', "price_month_thb": 165000, "price_night_thb": 5500},
            {"period": '1–15 декабря', "price_month_thb": 270000, "price_night_thb": 9000},
            {"period": '15–31 декабря', "price_month_thb": 450000, "price_night_thb": 15000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'RBC-218',
        "type": 'apartment',
        "title": 'Rawai beach condo 218',
        "district": 'Rawai',
        "bedrooms": 0,
        "sqm": '23',
        "view": 'garden view',
        "pool_access": 'common',
        "address": '111/20 Moo 6, Rawai, Mueang Phuket, Thailand, 83130',
        "map_link": 'https://maps.app.goo.gl/mJcTjFUHbz6GWQY3A?g_st=ic',
        "max_guests": None,
        "links": ['https://drive.google.com/drive/folders/1B_jjUaIrqDXwPGLuAG6kg6q3S_q_nBFb?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 81000, "price_night_thb": 2700},
            {"period": 'Февраль', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Март', "price_month_thb": 48000, "price_night_thb": 1600},
            {"period": 'Апрель', "price_month_thb": 33000, "price_night_thb": 1100},
            {"period": 'Май', "price_month_thb": 27000, "price_night_thb": 900},
            {"period": 'Июнь–Август', "price_month_thb": 15000, "price_night_thb": 500},
            {"period": 'Сентябрь', "price_month_thb": 18000, "price_night_thb": 600},
            {"period": 'Октябрь', "price_month_thb": 27000, "price_night_thb": 900},
            {"period": 'Ноябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": '1–15 декабря', "price_month_thb": 57000, "price_night_thb": 1900},
            {"period": '15–31 декабря', "price_month_thb": 81000, "price_night_thb": 2700},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'RBC-310',
        "type": 'apartment',
        "title": 'Rawai beach condo 310',
        "district": 'Rawai',
        "bedrooms": 1,
        "sqm": '37',
        "view": 'garden view',
        "pool_access": 'common',
        "address": '111/48 Moo 6, Rawai, Mueang Phuket, Thailand, 83130',
        "map_link": 'https://maps.app.goo.gl/mJcTjFUHbz6GWQY3A?g_st=ic',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/17WUMqIAGq4pKE47FlszGnyHhCF4e_vLF?usp=share_link', 'https://telegra.ph/Rawai-Beach-Condo-08-06'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Апрель', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 18000, "price_night_thb": 600},
            {"period": 'Сентябрь', "price_month_thb": 21000, "price_night_thb": 700},
            {"period": 'Октябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": '15–31 декабря', "price_month_thb": 90000, "price_night_thb": 3000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'RBC-102',
        "type": 'apartment',
        "title": 'Rawai beach condo 102',
        "district": 'Rawai',
        "bedrooms": 1,
        "sqm": '37',
        "view": 'garden view',
        "pool_access": 'common',
        "address": '111/16 Moo 6, Rawai, Mueang Phuket, Thailand, 83130',
        "map_link": 'https://maps.app.goo.gl/mJcTjFUHbz6GWQY3A?g_st=ic',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/1BVT5JgeYq32TTRDkCGiJzmH7tVBZzGRm?usp=share_link', 'https://telegra.ph/Rawai-Beach-Condo-08-06-2'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": 'Февраль', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Март', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Апрель', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Май', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Июнь–Август', "price_month_thb": 18000, "price_night_thb": 600},
            {"period": 'Сентябрь', "price_month_thb": 21000, "price_night_thb": 700},
            {"period": 'Октябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": 'Ноябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": '1–15 декабря', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": '15–31 декабря', "price_month_thb": 90000, "price_night_thb": 3000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'RBC-317',
        "type": 'apartment',
        "title": 'Rawai beach condo 317',
        "district": 'Rawai',
        "bedrooms": 0,
        "sqm": '22.7',
        "view": '',
        "pool_access": 'common',
        "address": '111/41 Moo 6, Rawai, Mueang Phuket, Thailand, 83130',
        "map_link": 'https://maps.app.goo.gl/mJcTjFUHbz6GWQY3A?g_st=ic',
        "max_guests": 2.0,
        "links": ['https://drive.google.com/drive/folders/1VfUNCXS-scyxoJDEgZ58zn7oyy6xx_I6?usp=drive_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 81000, "price_night_thb": 2700},
            {"period": 'Февраль', "price_month_thb": 60000, "price_night_thb": 2000},
            {"period": 'Март', "price_month_thb": 48000, "price_night_thb": 1600},
            {"period": 'Апрель', "price_month_thb": 33000, "price_night_thb": 1100},
            {"period": 'Май', "price_month_thb": 27000, "price_night_thb": 900},
            {"period": 'Июнь–Август', "price_month_thb": 15000, "price_night_thb": 500},
            {"period": 'Сентябрь', "price_month_thb": 18000, "price_night_thb": 600},
            {"period": 'Октябрь', "price_month_thb": 27000, "price_night_thb": 900},
            {"period": 'Ноябрь', "price_month_thb": 36000, "price_night_thb": 1200},
            {"period": '1–15 декабря', "price_month_thb": 57000, "price_night_thb": 1900},
            {"period": '15–31 декабря', "price_month_thb": 81000, "price_night_thb": 2700},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'TLR-G310',
        "type": 'apartment',
        "title": 'The Title Rawai II Phase G310',
        "district": 'Rawai',
        "bedrooms": 1,
        "sqm": '44',
        "view": 'fountain view',
        "pool_access": 'common',
        "address": '456/270 Moo 6, Rawai Sub-district, Muang Phuket District, Phuket, 83130',
        "map_link": 'Reception (main entrance)\nhttps://goo.gl/maps/fT5cRtgPDDcdzjEJ6\n\nBuilding G (entry is possible directly through the barrier)\nhttps://maps.app.goo.gl/ste828fA2g1CLVjs7',
        "max_guests": 3.0,
        "links": ['https://drive.google.com/drive/folders/1vfW02MQSt6nfaHnGUVeFntvxyxFF6EOS?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 120000, "price_night_thb": 4000},
            {"period": 'Февраль', "price_month_thb": 99000, "price_night_thb": 3300},
            {"period": 'Март', "price_month_thb": 84000, "price_night_thb": 2800},
            {"period": 'Апрель', "price_month_thb": 63000, "price_night_thb": 2100},
            {"period": 'Май', "price_month_thb": 51000, "price_night_thb": 1700},
            {"period": 'Июнь–Август', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Сентябрь', "price_month_thb": 30000, "price_night_thb": 1000},
            {"period": 'Октябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Ноябрь', "price_month_thb": 63000, "price_night_thb": 2100},
            {"period": '1–15 декабря', "price_month_thb": 84000, "price_night_thb": 2800},
            {"period": '15–31 декабря', "price_month_thb": 120000, "price_night_thb": 4000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'SUM-20/144',
        "type": 'villa',
        "title": 'Sumalee Villa 7',
        "district": 'Rawai',
        "bedrooms": 2,
        "sqm": None,
        "view": 'street view',
        "pool_access": 'private',
        "address": '20/144 Soi King Suksan 4, Rawai, Mueang Phuket District, Phuket 83130',
        "map_link": 'https://maps.app.goo.gl/BMSnuh9r9ztG5Kjq6?g_st=ic',
        "max_guests": 5.0,
        "links": ['https://drive.google.com/drive/folders/17kLJz5NhvbQ3JS2ioe1drStKVuAmUWp2?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 240000, "price_night_thb": 8000},
            {"period": 'Февраль', "price_month_thb": 135000, "price_night_thb": 4500},
            {"period": 'Март', "price_month_thb": 99000, "price_night_thb": 3300},
            {"period": 'Апрель', "price_month_thb": 75000, "price_night_thb": 2500},
            {"period": 'Май', "price_month_thb": 51000, "price_night_thb": 1700},
            {"period": 'Июнь–Август', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Сентябрь', "price_month_thb": 45000, "price_night_thb": 1500},
            {"period": 'Октябрь', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": 'Ноябрь', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": '1–15 декабря', "price_month_thb": 135000, "price_night_thb": 4500},
            {"period": '15–31 декабря', "price_month_thb": 240000, "price_night_thb": 8000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'VIP-F8',
        "type": 'villa',
        "title": 'VIP Rawai Villa F8',
        "district": 'Rawai',
        "bedrooms": 3,
        "sqm": '165',
        "view": 'jungle view',
        "pool_access": 'private',
        "address": '58/112 Moo 6, Soi Rouyphad Rawai Beach, Rawai, Muang, Phuket 83130',
        "map_link": 'https://maps.app.goo.gl/KQ8m7sRZaPWjAe2cA?g_st=ic',
        "max_guests": None,
        "links": ['https://drive.google.com/drive/folders/17ADOMzLs_akoCDdWJ1hgCJoU8vbAeheB?usp=share_link', 'https://telegra.ph/Rawai-VIP-Villas-08-06'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 270000, "price_night_thb": 9000},
            {"period": 'Февраль', "price_month_thb": 240000, "price_night_thb": 8000},
            {"period": 'Март', "price_month_thb": 180000, "price_night_thb": 6000},
            {"period": 'Апрель', "price_month_thb": 150000, "price_night_thb": 5000},
            {"period": 'Май', "price_month_thb": 93000, "price_night_thb": 3100},
            {"period": 'Июнь–Август', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": 'Сентябрь', "price_month_thb": 87000, "price_night_thb": 2900},
            {"period": 'Октябрь', "price_month_thb": 99000, "price_night_thb": 3300},
            {"period": 'Ноябрь', "price_month_thb": 114000, "price_night_thb": 3800},
            {"period": '1–15 декабря', "price_month_thb": 180000, "price_night_thb": 6000},
            {"period": '15–31 декабря', "price_month_thb": 270000, "price_night_thb": 9000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'BST-A4',
        "type": 'villa',
        "title": 'Boost Villa A4',
        "district": 'Rawai',
        "bedrooms": 4,
        "sqm": '250',
        "view": 'garden view',
        "pool_access": 'private',
        "address": '50/64 Moo 7, Rawai, Mueang Phuket, Thailand, 83130',
        "map_link": 'https://maps.app.goo.gl/9CprqPX6jX58h6W8A?g_st=ic',
        "max_guests": None,
        "links": ['https://drive.google.com/drive/folders/1Pi_yqlhEWTJ91d8EBGEbe40qaxpaYrLQ?usp=share_link'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 540000, "price_night_thb": 18000},
            {"period": 'Февраль', "price_month_thb": 420000, "price_night_thb": 14000},
            {"period": 'Март', "price_month_thb": 240000, "price_night_thb": 8000},
            {"period": 'Апрель', "price_month_thb": 210000, "price_night_thb": 7000},
            {"period": 'Май', "price_month_thb": 180000, "price_night_thb": 6000},
            {"period": 'Июнь–Август', "price_month_thb": 150000, "price_night_thb": 5000},
            {"period": 'Сентябрь', "price_month_thb": 135000, "price_night_thb": 4500},
            {"period": 'Октябрь', "price_month_thb": 180000, "price_night_thb": 6000},
            {"period": 'Ноябрь', "price_month_thb": 240000, "price_night_thb": 8000},
            {"period": '1–15 декабря', "price_month_thb": 300000, "price_night_thb": 10000},
            {"period": '15–31 декабря', "price_month_thb": 540000, "price_night_thb": 18000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
    {
        "id": 'SUK-20/154',
        "type": 'villa',
        "title": 'Suksan Villa 20/154',
        "district": 'Rawai',
        "bedrooms": 4,
        "sqm": '242.68',
        "view": 'garden view',
        "pool_access": 'private',
        "address": '20/154 Soi King Suksan 4, Rawai, Mueang Phuket District, Phuket 83100',
        "map_link": 'https://maps.app.goo.gl/ShEFUsi5E9vC4BY68?g_st=ic',
        "max_guests": None,
        "links": ['https://drive.google.com/drive/folders/10JqJtR7dOS7XyZVl4waJCCWugQx47gUn?usp=share_link', 'https://telegra.ph/Suksan-Villa-08-06'],
        "prices": [
            {"period": 'Январь', "price_month_thb": 390000, "price_night_thb": 13000},
            {"period": 'Февраль', "price_month_thb": 300000, "price_night_thb": 10000},
            {"period": 'Март', "price_month_thb": 240000, "price_night_thb": 8000},
            {"period": 'Апрель', "price_month_thb": 150000, "price_night_thb": 5000},
            {"period": 'Май', "price_month_thb": 114000, "price_night_thb": 3800},
            {"period": 'Июнь–Август', "price_month_thb": 105000, "price_night_thb": 3500},
            {"period": 'Сентябрь', "price_month_thb": 90000, "price_night_thb": 3000},
            {"period": 'Октябрь', "price_month_thb": 120000, "price_night_thb": 4000},
            {"period": 'Ноябрь', "price_month_thb": 165000, "price_night_thb": 5500},
            {"period": '1–15 декабря', "price_month_thb": 240000, "price_night_thb": 8000},
            {"period": '15–31 декабря', "price_month_thb": 390000, "price_night_thb": 13000},
        ],
        "currency": "THB",
        "description": '',
        "photos": [],
    },
]

# Всего объектов: 27


# ---------- Служебное: типы объектов и хелперы поиска ----------
PROPERTY_TYPES = {
    "villa": "🏡 Виллы",
    "apartment": "🏢 Апартаменты",
    "townhouse": "🏘 Таунхаусы",
}


def get_by_id(property_id: str):
    for p in PROPERTIES:
        if p["id"] == property_id:
            return p
    return None


def get_by_type(property_type: str):
    return [p for p in PROPERTIES if p["type"] == property_type]